version: "3"
services:
  bucket:
    image: mklean/baseline-microsuite:hdsearch_router_setalgebra_recommend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
        - /microsuite/MicroSuite:/home/data
    expose:
        - "50050"
    cap_add:
        - SYS_PTRACE
    deploy:
        restart_policy:
                condition: none
        placement:
                constraints: ["node.hostname == ${NODE0}"]
    command: >
        bash -c "wget https://akshithasriraman.eecs.umich.edu/dataset/HDSearch/image_feature_vectors.dat
                mv image_feature_vectors.dat /home
                cd /MicroSuite/src/HDSearch/bucket_service/service
                ./bucket_server /home/image_feature_vectors.dat 0.0.0.0:50050 2 -1 0 1"

  midtier:
    image: mklean/baseline-microsuite:hdsearch_router_setalgebra_recommend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
        - /microsuite/MicroSuite:/home/data
    expose:
        - "50051"
    cap_add:
        - SYS_PTRACE      
    deploy:
        restart_policy:
                condition: none
        placement:
                constraints: ["node.hostname == ${NODE1}"]
    command: >
        bash -c "wget https://akshithasriraman.eecs.umich.edu/dataset/HDSearch/image_feature_vectors.dat
                mv image_feature_vectors.dat /home
                while ! echo exit | nc bucket 50050; do sleep 1; done
                echo 'bucket launched'
                cd /MicroSuite/src/HDSearch/mid_tier_service/service
                touch bucket_servers_IP.txt
                echo "bucket:50050" > bucket_servers_IP.txt
                ./mid_tier_server 1 13 1 1 bucket_servers_IP.txt /home/image_feature_vectors.dat 2 0.0.0.0:50051 1 4 4 0"

  client:
    image: mklean/baseline-microsuite:hdsearch_router_setalgebra_recommend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
        - /microsuite/MicroSuite:/home/data
    cap_add:
        - SYS_PTRACE      
    deploy:
        restart_policy:
                condition: none
        placement:
                constraints: ["node.hostname == ${NODE2}"]
    command: >
        bash -c "wget https://akshithasriraman.eecs.umich.edu/dataset/HDSearch/image_feature_vectors.dat
                mv image_feature_vectors.dat /home
                while ! echo exit | nc midtier 50051; do sleep 1; done
                echo 'midtier launched'
                cd /MicroSuite/src/HDSearch/load_generator
                mkdir ./results
                ./load_generator_open_loop /home/image_feature_vectors.dat ./results/ 1 30 100 midtier:50051 dummy1 dummy2 dummy3"
